---
title: "Assignment 1: Introduction"
author: "Meg O'Brien"
output: pdf_document
---

## OVERVIEW

This exercise accompanies the introductory material in Environmental Data Analytics. 

## 1) Discussion Questions

1. What are your previous experiences with data analytics, R, and Git? Include both formal and informal training.

> Answer: I took a climate modeling course my sophomore year of undergraduate school, where I learned the basics of R and Git. We modeled climate feedback loops, and learned the basics of R programming and using GitHub. I still feel as though my knowledge of both R and Git are very basic and introductory level. 

2. Are there any components of the course about which you feel confident?

> Answer: Not totally. I feel like I am going to be learning a significant amount of the material for the first time. 

3. Are there any components of the course about which you feel apprehensive?

> Answer: I am slightly nervous about navigating the R and Github platforms, and understanding all of the terminology and coding functions. I think once I feel confident navigating both platforms and utilizing all of the functions, I will feel much more confident overall.

## 2) GitHub

Provide a link below to your forked course repository in GitHub. Make sure you have pulled all recent changes from the course repository and that you have updated your course README file, committed those changes, and pushed them to your GitHub account. 

> Answer: https://github.com/megobrien1/EDE_Fall2025.git

## 3) Knitting
When you have completed this document, click the `knit` button.This should produce a PDF copy of your markdown document. Submit this PDF to Canvas 
